### ISSUE TITLE
[Enhancement] Loading message or spinning wheel

### ISSUE THREAD

**Issue by lguariento** [omeka-s-modules/FacetedBrowse#11]
My faceted table is slow to load (sometimes even in the region of more than ten seconds) and it would be great if there was a waiting message or spinning wheel informing the user that the input has been registered and the results are loading.

[Example](https://boslit.glasgow.ac.uk/faceted-browse/3) (select 'Chinese' as original language, or subject 'Aesthetics', for instance).

**Comment by jimsafley** [comment]
We'll look into it. In the meantime you could add one line to asset/js/site/page.js. Change this :
```js
    queries.push(`faceted_browse_category_id=${facets.data('categoryId')}`);
    $.get(`${urlBrowse}?${queries.join('&')}`).done(function(html) {
```
To this:
```
    queries.push(`faceted_browse_category_id=${facets.data('categoryId')}`);
    sectionContent.text(Omeka.jsTranslate('Loading results…'));
    $.get(`${urlBrowse}?${queries.join('&')}`).done(function(html) {
```

**Comment by lguariento** [comment]
Can you let me know the line please? I get `Uncaught TypeError: Omeka.jsTranslate is not a function`

**Comment by jimsafley** [comment]
That's where the line should go. Your theme probably does not implement jsTranslate. In your theme's layout template just add the following after loading js/global.js.

```php
$this->jsTranslate();
``` 

Or you could just remove the call to `Omeka.jsTranslate()`.

**Comment by jimsafley** [comment]
Keep it open, please. We're considering the best way to do this, but it may take some time.

**Comment by jimsafley** [comment]
Feature added in 84742b812b5adb84849920e5d128fc959eb2f4ed
