### ISSUE TITLE
Styling of Title and Thumbnail on browse table

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/FacetedBrowse#13]
Not sure if this is a theme thing or a module thing, but it seems that the thumbnail and title need a bit of styling? I didn't notice earlier because I tested with all metadata items.
![Screenshot 2022-03-21 at 15-22-18 Photo browse · Photographs · SML Omeka S Test](https://user-images.githubusercontent.com/741480/159348788-2659cf0d-ad9c-423c-a571-f88561e7a4e3.png)

**Comment by kimisgold** [comment]
I can provide some better default styles.

**Comment by kimisgold** [comment]
Fixed in https://github.com/omeka-s-modules/FacetedBrowse/commit/faf106f045131f9e4edfb2411dc54d96a9cbab1e.
