### ISSUE TITLE
Text input for value facet

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#14]
This [forum post](https://forum.omeka.org/t/faceted-browse-text-box-for-value-facets/15207) describes a use case where an administrator would rather their end users enter text into a box than select from a menu of options. This would give the user more control over the results and avoid the pitfall of presenting too many options to the user.

My first thought is to modify the existing "Value" facet type to include a "Text input" select type. However, it's probably more feasible to add another "Value text" facet type and rename the existing type to "Value select." Then there's the matter of front-end behavior: should the results update at every key press, or should the user have to click a button to update the results?

**Comment by zerocrates** [comment]
For what they're specifically talking about is something extremely simple like Chosen a possibility?
