### ISSUE TITLE
Testing: Text input select type

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#15]
The [value-text-input](https://github.com/omeka-s-modules/FacetedBrowse/compare/value-text-input) branch introduces a text input "facet" that allows users to enter text to search items. It functions similarly to the "Full-text" facet type, but it's tied to a property. To test this, edit a category, add a "Value" facet, enter a name and property, select the "Text input" select type, then set the facet and save the category. Add the page to navigation and go to the public site. You should see a text input on the faceted browse page. Enter text into it. It should update the results while typing. If this works, go back and edit the category. Add a "Value" facet for every select type. Test all of them on the public side. They should all work together.

**Comment by katknow** [comment]
This seems to work well and the various select types can work together. The only thing is that it only updates while typing when "contains" is enabled, which makes sense, but I wanted to note that since it wasn't specified. If that's okay, I think this is good to go.

**Comment by jimsafley** [comment]
It should auto-update for all query types, not just "Contains." It doesn't auto-update when typing when you have, say, "Is exactly" set?

**Comment by katknow** [comment]
On the others I get this (I was searching "daphne")

![image](https://user-images.githubusercontent.com/84726696/173124979-fccba44e-730f-461d-b38a-31d2047ae2ce.png)

and it updates to the 0 every time I add a letter until I have the full search term then it pulls them

**Comment by jimsafley** [comment]
Ah, yes, that's expected.
