### ISSUE TITLE
Laminas issue with last release 1.1.1 and site languages

### ISSUE THREAD

**Issue by saponidas** [omeka-s-modules/FacetedBrowse#20]
Hi, I am facing the next issue with a fresh intallation when the main site language or sites is other than default/english

Ubuntu 22.04
Apache/2.4.52 
PHP 7.4.30 
Mysql  8.0.29

--
Omeka S V_3.2.1 fresh installation
Faceted Browse 1.1.1
Note 1: The same behavior occurs with Value Suggest v_1.12.0
Note2:  the previous release of both plugins (1.1.0 and v_1.11.0) seems to work fine.

--

- Active the plugin. Then **Change the language to other than default/english**  at the main settings or at site settings. Eg. Francais or Spanish and reload the frontend

`Laminas\I18n\Exception\RuntimeException:`
`Plural rule of merging text domain is not compatible with the current one in /var/www/domain.com/public_html/vendor/laminas/laminas-i18n/src/Translator/TextDomain.php:100`

**Stack trace:**
Laminas\I18n\Exception\RuntimeException: Plural rule of merging text domain is not compatible with the current one in .../public_html/vendor/laminas/laminas-i18n/src/Translator/TextDomain.php:100
Stack trace:
#0 Apache/2.4.52 /public_html/vendor/laminas/laminas-i18n/src/Translator/Translator.php(705): Laminas\I18n\Translator\TextDomain->merge()
#1 .../public_html/vendor/laminas/laminas-i18n/src/Translator/Translator.php(616): Laminas\I18n\Translator\Translator->loadMessagesFromPatterns()
#2 .../public_html/vendor/laminas/laminas-i18n/src/Translator/Translator.php(440): Laminas\I18n\Translator\Translator->loadMessages()
#3 .../public_html/vendor/laminas/laminas-i18n/src/Translator/Translator.php(355): Laminas\I18n\Translator\Translator->getTranslatedMessage()
#4 .../public_html/application/src/I18n/Translator.php(25): Laminas\I18n\Translator\Translator->translate()
#5 .../public_html/vendor/laminas/laminas-mvc-i18n/src/Translator.php(71): Omeka\I18n\Translator->translate()
#6 .../public_html/vendor/laminas/laminas-i18n/src/View/Helper/Translate.php(37): Laminas\Mvc\I18n\Translator->translate()
#7 .../public_html/application/view/omeka/site/item/browse.phtml(17): Laminas\I18n\View\Helper\Translate->__invoke()
#8 .../public_html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/hismec...')
#9 .../public_html/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render()
#10 .../public_html/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render()
#11 .../public_html/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren()
#12 .../public_html/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render()
#13 .../public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#14 .../public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners()
#15 .../public_html/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent()
#16 .../public_html/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest()
#17 .../public_html/index.php(21): Laminas\Mvc\Application->run()
#18 {main}

Best,

**Comment by jimsafley** [comment]
Thanks for the bug report. It'll be fixed in the next release, which should be withing the month. I have released a bugfix version of ValueSuggest [here](https://github.com/omeka-s-modules/ValueSuggest/releases/download/v1.12.1/ValueSuggest-1.12.1.zip).
