### ISSUE TITLE
Sorting problems with Faceted Browse

### ISSUE THREAD

**Issue by jbhistorian** [omeka-s-modules/FacetedBrowse#22]
I would like to bring to your attention issues with sorting in the Faceted Browse module.

We use (and love) the Faceted Browse module on our Omeka S website New Jersey Slavery Records (affiliated with the On These Grounds project where we work with Sharon Leon). Our site uses the Foundation theme.

Here’s one of our Faceted Browse pages: https://records.njslavery.org/s/doc/faceted-browse/1

At the top, there is the Sort button, a drop-down list of columns that can be used for sorting, and a drop-down list to select “Ascending” or “Descending” order. We are experiencing two distinct issues with this sorting mechanism and we would like to find solutions.

Issue 1. The sorting mechanism works for the first column “Event” (this is the Title of the resource which links to the resource) and for the second column “Date” (data types used: date timestamp or date interval). However, the sorting mechanism does not work for the third and fourth columns, which are “Location” and “Enslaver.” Trying to sort these columns in either Ascending or Descending order changes the order of the items on the page, but there doesn’t seem to be any rhyme or reason to the resulting order. I can only assume that this problem has something to do with the data type for these fields. Both of these fields have the data type of Omeka S Resource by ID. It's not sorting them by resource ID either, though, as you can see in the screenshot below where we get: New York, NY (id 26), Wood Lawn Mansion (id 53), then back to New York, NY (id 26). We would like to be able to sort these columns alphabetically by the title of the linked Omeka S Resource that is displayed here.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/89092402/194423762-a6110e9a-8cc5-4eb4-84ea-b44b57df59f5.png">

Issue 2. As I mentioned, sorting normally works as expected for columns 1 and 2 (Event and Date). One of the facets set up on this page is “Full-text search.” When the “full-text search” facet is used, suddenly all ability to sort the records by column 1 and column 2 is also lost. (This behavior seems to happen only with the "full-text search" facet, the other facets don't cause this problem.)

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/89092402/194424405-6a99b292-86c3-40b8-9fe3-1130686b4981.png">

**Comment by jimsafley** [comment]
Thank you for the detailed bug report. You seem to have found two idiosyncrasies with Omeka S search that may not have straightforward solutions.

You are correct to assume that Issue 1 has something to do with the "Omeka resource" data type. This is consequence of how Omeka S sorts by value, so it is not exclusive to this module. I've created an [issue](https://github.com/omeka/omeka-s/issues/1953) on the Omeka S repository, though, I'm not confident that a fix is forthcoming.

Issue 2 is also something that is not exclusive to this module. Full-text searches will always override sorting with an opaque "sort-by-relevance" because relevance is intrinsic to full-text searches. Certainly not ideal from a UX perspective, but this is expected behavior.

**Comment by jbhistorian** [comment]
Thank you, Jim. For issue #1, if the sorting can't be fixed in the near term, I wonder if we could instead have more control over what options are displayed in the dropdown box for sorting in the Faceted Browse module. The default behavior is that if I have 4 columns on the faceted browse page, then all 4 will automatically be displayed in the sort dropdown box. Is there any way we could control that behavior and tell the module not to display the last 2 options when we know that it won't properly sort the results using that column anyway? Of course, it would be ideal if we could sort by any column regardless of data type, but if sorting won't work, it would be good if we could manually eliminate options from the dropdown to minimize user confusion.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/89092402/194441171-4ea57843-5988-4724-a4f0-2e6e57e6d994.png">
