### ISSUE TITLE
Documentation: Exclude column from sort by

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#24]
See #23

**Comment by katknow** [comment]
I was just cleaning out my notifications and saw that I had missed this issue--my apologies! [I've added a brief paragraph under the Columns heading describing the exclude sort by function.](https://github.com/katknow/Drafts/blob/4c6fb5a9207aaa9d395f541e0f8a2f31eeb1d454/facetedbrowse.md) Please let me know what changes you'd like me to make and I can get it added to the documentation ASAP.

**Comment by jimsafley** [comment]
Looks good to me.
