### ISSUE TITLE
Faceted Browse not loading results on first page load

### ISSUE THREAD

**Issue by mufticsanjin** [omeka-s-modules/FacetedBrowse#27]
Hello,
this module is really great.

One strange issue we discovered is that on one of our faceted browse pages, the results don't load when you first load the page. It requires one to click on back, then on the category before getting the full results: [https://ibali.uct.ac.za/s/ctdps/faceted-browse/5](https://ibali.uct.ac.za/s/ctdps/faceted-browse/5). The set up of the pages is similar from other faceted browse pages, albeit they have different themes running on those sites. For example, this one works fine:[https://ibali.uct.ac.za/s/rephotosa/faceted-browse/11](https://ibali.uct.ac.za/s/rephotosa/faceted-browse/11)

We are running 3.2.1 Omeka with Faceted-Browse module: 1.2.0

Any idea what this might be?

**Comment by jimsafley** [comment]
There's a `TypeError` error on that page that prevents further execution of JavaScript. It appears that the theme you're using for the ctdps site doesn't load the [global.js script](https://github.com/omeka/omeka-s/blob/develop/application/asset/js/global.js). Try loading that script in the theme's layout like this:

```php
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
```

**Comment by mufticsanjin** [comment]
Thanks so much @jimsafley !
That was fast.

I had a look at the ctdps theme and saw that it indeed did have the call for that script but it did not have 
`$this->jsTranslate();`
which i found in the other theme.

I added it and it loaded it right up. Thanks so much for pointing me in the right direction!
