### ISSUE TITLE
Spinning wheel not shown

### ISSUE THREAD

**Issue by lguariento** [omeka-s-modules/FacetedBrowse#28]
Hello,

I just upgraded to Omeka 4.0.0 and I have the latest FacetedBrows plugin. The spinning wheel is not shown when waiting to load results. I do see the spinning container with `loading` class, the icon is not there. Is it a wider FontAwesome issue?

![loading](https://user-images.githubusercontent.com/10143842/214624758-0cc7ae2f-283d-4816-8204-baa6b85bb3e4.png)

**Comment by kimisgold** [comment]
The module needs to be updated to specify the necessary weight to make the icon appear. There should be a fix shortly.
