### ISSUE TITLE
Facet with data type 'Omeka resource' does not (yet) work

### ISSUE THREAD

**Issue by m-art-in** [omeka-s-modules/FacetedBrowse#30]
I have only recently started using the module and would like to create a facet. However, my attribute is not of type "Text" but of type "Omeka Resource" as a link to another item. Therefore the facet does not work. 

As a workaround, I thought about cloning the field and creating it again as a text field. But of course it would be nicer if it would work directly.

![grafik](https://github.com/omeka-s-modules/FacetedBrowse/assets/15324884/7d04417c-4661-40c4-949e-3fa913c64dc7)

it#s about the field "References", which can contain a list of persons. What is the best approach to proceed?

**Comment by zerocrates** [comment]
I think we'll consolidate this to just be on the forums.
