### ISSUE TITLE
Auto-remove FB pages from Navigation when deleted

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/FacetedBrowse#33]
Is there a way for Faceted Browse to modify the Navigation when a FB page is deleted?

I'm guessing no; I don't think there is a precedent for this. I know deactivating modules makes "[Missing Page]" appear instead of the page titles wherever things are in the nav - for FB and Mapping at least. I can't think of other page-creating modules offhand.

**Comment by jimsafley** [comment]
There's no reliable way to remove the link given the way we store navigation data. Users should either delete the link from navigation or change the faceted browse page.
