### ISSUE TITLE
Selecting from multiple-selection list shouldn't rearrange

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/FacetedBrowse#37]
When a checkbox is clicked, there's no need to have the facet move out of its order and to the top. Re #36, the order of facets would seem to imply frequency, in most other interfaces. Whether that gets fixed or not, I think this movement is pointless and not very user-friendly. 

https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/bc9d1244-880b-4474-9e2a-f14f46e4e20f

**Comment by jimsafley** [comment]
The movement to the top is in line with other faceted searches I've seen. As an example, Amazon's facets do this most of the time. It's particularly needed when lists have been truncated else selected items may not be visible.
