### ISSUE TITLE
Table styling with added columns

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/FacetedBrowse#39]
From https://github.com/omeka-s-modules/FacetedBrowse/issues/32#issuecomment-1811535979, some flexible table styling is needed to accomodate all (most) possible columns. 
Probably need classes and IDs so users can manually style their chosen columns once set up, keeping in mind CSS Editor and its limitations. 
Resource titles should sit inline with thumbnails, unless compressed; item sets and longer text fields like description should be truncated so as not to have infinitely tall table rows. 
The "Ascending/Descending" selector is too short.
And then, of course, we'll have to check it on mobile and test for accessibility.

**Comment by kimisgold** [comment]
What theme are you using? It looks like Cozy, but mine looks fairly different.

<img width="1194" alt="Screenshot 2023-11-15 at 3 43 27 PM" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/606764/5e569974-8028-448c-bca2-b92bd91e12fb">

**Comment by allanaaa** [comment]
I think it could use work in Default, Thanks Roy, the Daily, and Foundation.

It looks _okay_ in Center Row and Papers. Center Row has the thumbnail/title problem.

<img width="964" alt="Screenshot 2023-11-15 at 16 19 44" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/a9f44c33-dbb6-43cb-9c19-cad6d4b59e31">

Papers has the cut-off "ascending/descending" selector problem. And I am not a fan of the thumbnails centred in the height of the title rather than at the top of the row. 

<img width="863" alt="Screenshot 2023-11-15 at 16 18 29" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/894ec9fe-7b67-493c-b7e4-2f795b67e5a2">

I realize each theme will do different things to e.g. the thumbnail size, but I wonder if we should standardize that a bit in the case of this module, since the table can eat a lot of space. Center Row already has a fixed page width, so it makes sense to have tiny thumbnails there, for example. I'm also not clear on why the sidebar/content ratio is sometimes 70/30 and sometimes 75/25. 

In Freedom the table looks okay, but I think the sidebar isn't meant to look like this, @nelsonamaya82? 

<img width="1430" alt="Screenshot 2023-11-15 at 16 13 51" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/3e00b1d3-9cc6-498b-a942-af78a954abd2">

**Comment by kimisgold** [comment]
Thanks, listing those themes will help me provide some default styles. I've drafted some that are ready to pull.

**Comment by nelsonamaya82** [comment]
Thanks @allanaaa, no that shouldn't look like this in Freedom, will work on fixing it.

**Comment by kimisgold** [comment]
Is this still a faceted browse view or a different view?

**Comment by kimisgold** [comment]
I've gone in and consolidated Thanks Roy's resource link styles, including applying them to faceted browse. Pull Thanks Roy to test.

**Comment by allanaaa** [comment]
> I've gone in and consolidated Thanks Roy's resource link styles, including applying them to faceted browse. Pull Thanks Roy to test.

I wasn't expecting the items' thumbnails themslves to change, only the way linekd resources will show in FB columns when applicable. 
Also, the bullet points are not vertically centred.

<img width="1147" alt="Screenshot 2023-11-16 at 15 20 50" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/15cd6d99-578f-430a-a509-4b9d79051f81">

The live page is here: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/faceted-browse/2

Let me know if you want to hop on a screenshare and talk this stuff through in more detail.

**Comment by allanaaa** [comment]
The max-width of 30 on resource-name is resulting in things like this:

<img width="882" alt="Screenshot 2023-11-16 at 15 39 40" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/6e265933-1e90-4548-9eae-35f71596ee76">

**Comment by kimisgold** [comment]
The live site helps, thanks!

**Comment by kimisgold** [comment]
@allanaaa In FacetedBrowse, I've added a jquery plugin that allows users to navigate table columns horizontally with navigation buttons. It's ready for a look on most themes; Thanks Roy is having issues that I'm looking into.

**Comment by allanaaa** [comment]
I really like that. Having columns drop off when there simply isn't enough space is clever. The interface will need some explanation of the buttons. Maybe they can go inside the header of the table? And disappear when all the columns are in view? 

<img width="1150" alt="Screenshot 2023-11-21 at 14 14 21" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/ae60c992-a09e-4943-a466-68fadbb12391">

Looks really good on The Daily. I'm still not sure how the width of the columns is being determined, and I am not a fan of vertical-align:middle. But this is a definite improvement.

**Comment by kimisgold** [comment]
I figured out the issues with Thanks Roy, so the table experience should be improved. (The `<body>` had a `word-break` rule that was allowing for those ugly thin columns and throwing off width calculations.) I'll think on your other comments. We're somewhat limited on how much we can manipulate the navigation elements from the plugin, but improvements are worth bringing up.

**Comment by allanaaa** [comment]
Okay. Thanks Roy has some overflow happening now; so does Default, Papers, and Foundation. 

<img width="1185" alt="Screenshot 2023-11-21 at 17 47 46" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/dbdef006-8fa5-4db7-8278-a4a1e1af17c9">
<img width="1239" alt="Screenshot 2023-11-21 at 17 57 43" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/527e287b-28d5-4249-b5f7-3c73e1657965">
<img width="1246" alt="Screenshot 2023-11-21 at 17 59 42" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/4463ccde-848f-447a-9056-487b71eb3333">


I would say
- make sure the "ascending/descending" selector is the right width in all themes
- make sure there's always some padding around thumbnails and table cell contents
- fix the bullet points for item sets (maybe just remove them if they can't be made to look good)
- for any theme that's got a really fixed width (e.g. Thanks Roy's table can only be 70% of 75% of 95% of the screen width, minus padding; Foundation is only 70% of 75% of the screen, etc.) I think we'll need to either enforce column min-widths and try to run them off the screen

Are my main priorities, if we can make them happen.

**Comment by kimisgold** [comment]
@allanaaa I've made revisions to Papers to try to address your main priorities. Can you pull, review, and see if they meet standards? If they look good, I can use that as a reference point when addressing the other themes.

**Comment by allanaaa** [comment]
It's an improvement for sure, in Papers and Thanks Roy. 

<img width="1175" alt="Screenshot 2023-11-29 at 15 28 40" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/b37e95a5-fb59-4bb3-bf51-6735793b0e83">
<img width="1114" alt="Screenshot 2023-11-29 at 15 28 19" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/500df355-5c9b-4bd3-ac96-b42f4b8a5af7">

But I don't know why the text overflow is still happening. I assume if there isn't enough space to accomodate the text then the last column should disappear.

<img width="1189" alt="Screenshot 2023-11-29 at 15 39 27" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/aa069412-2838-4465-ba82-a5a531d08630">

Do you need access to a site with all this stuff set up?

**Comment by kimisgold** [comment]
Yes, if you could provide me with the live example, that'd be a huge help.

**Comment by kimisgold** [comment]
I used your previous link as a reference and attempted a fix. Go ahead and pull it to see if it helps.
