### ISSUE TITLE
Editing page should show page title

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/FacetedBrowse#40]
![FacetedBrowse-SearchQuery](https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/e271ed20-adba-428b-9734-c910b1914f0e)

Once you've created a new page and set a page title, can it be displayed in the breadcrumb when doing further editing on the categories and columns?

**Comment by jimsafley** [comment]
Given the space constraints and the benefit of consistent wording in the breadcrumbs, I prefer not to display the page title there. Will a title attribute suffice?

**Comment by allanaaa** [comment]
I'm not sure what that means. You don't think you can fit `"Pages" > [Page Title] > "Page edit" > "Category edit"` in the breadcrumb?
