### ISSUE TITLE
Allow default sort to be customized

### ISSUE THREAD

**Issue by kalbers** [omeka-s-modules/FacetedBrowse#41]
Either pick up the general sort setting from the site settings, or add an option for the page in general.

**Comment by jimsafley** [comment]
WIP in the [category-default-sort](https://github.com/omeka-s-modules/FacetedBrowse/compare/category-default-sort) branch.

**Comment by jimsafley** [comment]
Feature added in 5de1e125ead563d8c6505a13e01b31d68c9f6282
