### ISSUE TITLE
Testing: Default sort

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#42]
The [category-default-sort](https://github.com/omeka-s-modules/FacetedBrowse/compare/category-default-sort) branch adds the ability to set a default sort on the public faceted browse. On the add and edit category pages you'll see two new select menus: "Default sort by" and "Default sort order". To test this, set a default sort by and sort order and check to see if the corresponding public page respects the default sort. You may need to test this on a new category because the public pages cache the sort, so a previous sort may already be set. Note that you'll need to upgrade the module.

**Comment by allanaaa** [comment]
This is designed to load all the columns currently set? It's missing the item set column on one of my categories, even though "exclude by" is not checked. Is that expected?

My understanding at one point was that whenever things are sorted, either ascending or descending, empty values would come at the end, not the beginning. In this case empty values seem to come at the beginning of ascending. Can you fact-check me on that?

**Comment by jimsafley** [comment]
The item set column is not sortable given that there may be more than one item set, and therefore not included in the sort menu.

Empty values do come at the beginning of ascending order. The database considers NULL values lower than any non-NULL value.
