### ISSUE TITLE
FacetedBrowse is not theme friendly

### ISSUE THREAD

**Issue by flamsens** [omeka-s-modules/FacetedBrowse#50]
The FacetedBrowse module duplicates the default view code to display resource lists, but introduces custom styles for resource list when viewed on a faceted browse page, making the resource items look different than originaly styled by the site theme.

To support FacetedBrowse and ensure a consistent site look and feel, theme builders have to add extra css code to overwrite the styles introduced by the FacetedBrowse module. This makes the module not theme friendly.

In my opinion, a module should only style newly added features, not restyle existing code blocks.

**Comment by kimisgold** [comment]
I've reviewed the default view and found that a lot of the styles are accommodating differences between the resource list markup in the module and the core. The mismatch seems like an oversight, so I've synced them again and removed the excess css.
