### ISSUE TITLE
[Enhancement] Possibility of adding all available values in one go

### ISSUE THREAD

**Issue by lguariento** [omeka-s-modules/FacetedBrowse#6]
I have installed the plugin in my Omeka S 3.1.1. I'd like to show all the available values of my field, since there are a lot of them. I click on 'show all available values' and save.

The values are not shown on the website, and the next time I enter the edit page of that category the 'show all available values' is unchecked again. Is this a bug or am I doing something wrong?

![Screenshot 2022-02-06 at 14-23-21 Creator · Edit Category · Faceted Browse · BOSLIT](https://user-images.githubusercontent.com/10143842/152685453-07540137-46dc-40b4-9d82-a9bf113bce86.png)
'

**Comment by lguariento** [comment]
PS: is that list supposed only to show the data as a convenience, and then you have to copy-paste those values? If so, is there a way to have something like an 'add all' button?

**Comment by lguariento** [comment]
@jimsafley Amazing, thanks. Let me know if you need help testing.

**Comment by lguariento** [comment]
Even better, perhaps an automatic synchronisation with the values would be great. For example, what happens when adds a new creator in the example above? I'd need to add it manually to the list of facets.

**Comment by jimsafley** [comment]
> automatic synchronisation

It's a good idea for sure, but detecting a new value, etc. would have to be run during every modification to every resource—an expensive process that's hard to justify for a relatively minor convenience.

**Comment by jimsafley** [comment]
The add all feature was tested and merged and will be available in the next release. No ETA as of now.
