### ISSUE TITLE
Testing: Add all feature

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#8]
The [add-all branch](https://github.com/omeka-s-modules/FacetedBrowse/compare/add-all) introduces a way for administrators to quickly add values, resource templates, resource classes, and item sets to their facets. Add a facet to a category (one at a time), click on "Show all available...", and then the "Add all" button. This should populate the above form element with all the resulting stuff.

**Comment by katknow** [comment]
Other than the error message I get when it's trying to process too many things, this works for values, resource templates, resource classes, and item sets.
